version: '3.8'

services:
  mysql:
    image: mysql:8
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: 686905439
      MYSQL_DATABASE: proyecto
      MYSQL_USER: david
      MYSQL_PASSWORD: 686905439
    volumes:
      - mysql_data:/var/lib/mysql
    ports:
      - "3306:3306"

  backend:
    build: ../backend
    container_name: backend
    ports:
      - "3001:3000"
    environment:
      - MYSQL_HOST=mysql
      - MYSQL_PORT=3306
      - MYSQL_USER=david
      - MYSQL_PASSWORD=686905439
      - MYSQL_DATABASE=proyecto
      - JWT_SECRET=686905439
    depends_on:
      - mysql

  frontend:
    build: ../frontend
    container_name: frontend
    ports:
      - "3000:3000"
    environment:
      - NEXT_PUBLIC_API_URL=http://localhost:3001

volumes:
  mysql_data:
