apiVersion: v1
kind: Service
metadata:
  name: backend-service
  namespace: fastcontract-dev
  labels:
    app: backend-Service
spec:
  type: NodePort
  selector:
    app: backend
  ports:
    - port: 31001
      targetPort: 31001
      nodePort: 31001
