apiVersion: v1
kind: Service
metadata:
  name: backend-service
  namespace: fastcontract-dev
  labels:
    app: backend-Service
spec:
  selector:
    app: backend
  ports:
    - port: 80
      targetPort: 31001
  type: ClusterIP
